# Generated by Django 5.1.7 on 2025-05-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, help_text='Automatically generated from email', max_length=150, null=True, unique=True, verbose_name='Username'),
        ),
    ]
