# Generated by Django 5.1.7 on 2025-05-12 15:18

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ColdRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Cold Room Name')),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='Use map widget to select location', srid=4326, verbose_name='Geographic Location')),
                ('capacity', models.PositiveIntegerField(help_text='Total storage units (boxes/pallets) available', verbose_name='Storage Capacity')),
                ('temp_min', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Minimum Temperature')),
                ('temp_max', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Maximum Temperature')),
                ('temp_unit', models.CharField(choices=[('C', 'Celsius'), ('F', 'Fahrenheit')], default='C', max_length=10, verbose_name='Temperature Unit')),
                ('availability_schedule', models.JSONField(blank=True, default=dict, help_text='JSON structure defining available time slots', verbose_name='Availability Calender')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(limit_choices_to={'user_type': 'COLD_ROOM_OWNER'}, on_delete=django.db.models.deletion.CASCADE, related_name='cold_room', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cold Room',
                'verbose_name_plural': 'Cold Rooms',
                'indexes': [models.Index(fields=['is_verified', 'capacity'], name='coldroom_verified_capacity_idx'), django.contrib.postgres.indexes.GistIndex(fields=['location'], name='coldroom_location_gist')],
            },
        ),
    ]
