# Generated by Django 5.1.7 on 2025-05-12 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coldrooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ColdRoomVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10, verbose_name='Verification Status')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('Verification_notes', models.TextField(blank=True, verbose_name='Admin Notes')),
                ('documentation', models.FileField(blank=True, null=True, upload_to='coldroom/verifications/', verbose_name='Verification Documents')),
                ('cold_room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='coldrooms.coldroom')),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cold Room Verification',
                'verbose_name_plural': 'Cold Room Verifications',
            },
        ),
    ]
